export * from './RatingSection';
export * from './ReviewsSection';
export * from './AmenitiesSection';
export * from './HotelDesc';
export * from './HotelMap';
export * from './RatingPop';
export * from './ReviewsPop';
export * from './AmentiesPop';
export * from './DescPop';
